### ISSUE TITLE
Failed running libsvm command

### ISSUE THREAD

**Issue by kenlog** [akondas/code-review-estimator#1]
Hello @akondas when I try to run the command bin / console estimate: github or estimate: wizard
![code-estimator](https://user-images.githubusercontent.com/11728231/53336877-f0d7c800-38ff-11e9-94df-607a292d817f.jpg)

Where am I wrong? Thank you

**Comment by akondas** [comment]
Check if `/var/www/code-review-estimator/vendor/php-ai/php-ml/var` have permission to write

**Comment by kenlog** [comment]
I had checked the possibility of writing, but despite having the write permissions fails always running the libsvm command.
I have certato on other similar problems and I tried to execute various suggestions but still remains the error. I'll try to figure out what's wrong with the time available. In any case, thank you @akondas I like this repository, only that it still does not allow me to try it. :persevere:

**Comment by kenlog** [comment]
@akondas Oops sorry I think I understand. In order to work it must first archive the data set, giving the command `bin/console train` so it works great! :+1: 

![bin-console](https://user-images.githubusercontent.com/11728231/53565758-96867380-3b5a-11e9-8a24-40916bb71352.png)

**Comment by akondas** [comment]
Great, thanks for info.

**Comment by keloniton** [comment]
Hello, The same problem here. I have installed libsvm and svm is loaded in my phpinfo.php. Wheren i run svm code i get error "Failed running libsvm command". I also checked writing permission in vendor....var, i changed them all to 777. but still the same problem. Please help me with it.

**Comment by akondas** [comment]
As a rule, a more specific reason is given after the colon why this command is not working, can you paste a more detailed error dump?

**Comment by andrespaz1991** [comment]
Hello friend, I have used the library on my local windows xampp server, but when uploading it to a linux hosting, it gives me the following error, apparently it is because it only finds svm-train for windows or mac. Can you help me? andres.paz1991@gmail.com from Colombia
#########
Fatal error: Uncaught Phpml\Exception\LibsvmCommandException: Failed running libsvm command: "/home2/pastofuturo/rvi.pastofuturo.org.co/rvi/red2/vendor/php-ai/php-ml/bin/libsvm/svm-train-osx -s 0 -t 0 -c 1 -n 0.500000 -d 3 -r 0 -p 0.100000 -m 100.000000 -e 0.001000 -h 1 -b 0 '/home2/pastofuturo/rvi.pastofuturo.org.co/rvi/red2/vendor/php-ai/php-ml/var/phpml6014dac4cc60b0.02975594' '/home2/pastofuturo/rvi.pastofuturo.org.co/rvi/red2/vendor/php-ai/php-ml/var/phpml6014dac4cc60b0.02975594-model'" with reason: "" in /home2/pastofuturo/rvi.pastofuturo.org.co/rvi/red2/vendor/php-ai/php-ml/src/SupportVectorMachine/SupportVectorMachine.php:164 Stack trace: #0 /home2/pastofuturo/rvi.pastofuturo.org.co/rvi/red2/vendor/php-ai/php-ml/src/Pipeline.php(56): Phpml\SupportVectorMachine\SupportVectorMachine->train(Array, Array) #1 /home2/pastofuturo/rvi.pastofuturo.org.co/rvi/red2/php-ml-examples-master/classification/bbcPipeline.php(28): Phpml\Pipeline->train(Array, Array) #2 {main} thrown in /home2/pastofuturo/rvi.pastofuturo.org.co/rvi/red2/vendor/php-ai/php-ml/src/SupportVectorMachine/SupportVectorMachine.php on line 164

**Comment by akondas** [comment]
@andrespaz1991 looks like your linux server is recognised as mac instance: you can see in this error message: `svm-train-osx`. Php-ml contains libsvm for linux, but in your case the operating system was probably misdiagnosed. Could you please return the value of a `PHP_OS` variable (from your linux server): 
```php
var_dump(PHP_OS); // or echo
```

**Comment by superdev43** [comment]
@akondas 
Hello, I am so happy to see you.
I have found the same error like Mr.andrespaz1991.

The result of PHP_OS is as following:
var_dump(PHP_OS)
---Linux---

I am sorry to bother you, but please help me in detail, thank you.
